version: '3'
services:
  flask-app:
    build: .
    container_name: WOG_container
    ports:
      - "8777:8777"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0
